- name: Deploy Azure Resource Manager (ARM) Template
  uses: Azure/arm-deploy@v1.0.9
  with:
    # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'managementgroup', 'subscription'
    scope: resourcegroup
    # Override the Subscription Id set by Azure Login.
    subscriptionId: # ${{ secrets.AzureSubscriptionId }}
    # Specify the Id for the Management Group, only required for Management Group Deployments.
    managementGroupId: # optional
    # Provide the target region, only required for management Group or Subscription deployments.
    region: 'brazilsouth'
    # Provide the name of a resource group, only required for resource Group deployments.
    resourceGroupName: $prodResourceGroupName
    # Specify the path or URL to the Azure Resource Manager template.
    template: 'azure/azuredeploy.json'
    # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group) or Validate (only validates the template).
    deploymentMode: # optional
    # Specifies the name of the resource group deployment to create.
    deploymentName: # optional
    # Supply deployment parameter values.
    parameters: 'azure/azuredeploy.parameters.json'
    # Specify whether to fail the action if some data is written to stderr stream of az cli. Valid values are: true, false
    failOnStdErr: # optional, default is true
    # Specify any additional arguments for the deployment.
    additionalArguments: # optional